---
spring:
  datasource.url: jdbc:mysql://localhost:3306/test
  datasource.username: root
  datasource.password: Mysqlewq1123!@
  jpa.hibernate.ddl-auto: update
  jpa.show-sql: true
  pa.properties.hibernate.format_sql: true
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

process.settings:
  list-process-ids: GMDR
  maximum-pool-size: 100
  max-pending-queue-size: 10000
  #get merchant deposit result process
  GMDR: { running: true, restart: false, warning-time: 2000, cancel-time: 2000 }
  name: trung

merchant-info.settings:
  request-timeout: 2000
  read-timeout: 2000